<?php

class TokenStaticMap{
    public static $map1 = array(
        0x01 => 'xmlstreamstart',
        0x02 => 'xmlstreamend',
        0x03 => 'account',
        0x04 => 'ack',
        0x05 => 'action',
        0x06 => 'active',
        0x07 => 'add',
        0x08 => 'after',
        0x09 => 'all',
        0x0a => 'allow',
        0x0b => 'apple',
        0x0c => 'audio',
        0x0d => 'auth',
        0x0e => 'author',
        0x0f => 'available',
        0x10 => 'bad-protocol',
        0x11 => 'bad-request',
        0x12 => 'before',
        0x13 => 'bits',
        0x14 => 'body',
        0x15 => 'broadcast',
        0x16 => 'cancel',
        0x17 => 'category',
        0x18 => 'challenge',
        0x19 => 'chat',
        0x1a => 'clean',
        0x1b => 'code',
        0x1c => 'composing',
        0x1d => 'config',
        0x1e => 'contacts',
        0x1f => 'count',
        0x20 => 'create',
        0x21 => 'creation',
        0x22 => 'debug',
        0x23 => 'default',
        0x24 => 'delete',
        0x25 => 'delivery',
        0x26 => 'delta',
        0x27 => 'deny',
        0x28 => 'digest',
        0x29 => 'dirty',
        0x2a => 'duplicate',
        0x2b => 'elapsed',
        0x2c => 'enable',
        0x2d => 'encoding',
        0x2e => 'encrypt',
        0x2f => 'error',
        0x30 => 'event',
        0x31 => 'expiration',
        0x32 => 'expired',
        0x33 => 'fail',
        0x34 => 'failure',
        0x35 => 'false',
        0x36 => 'favorites',
        0x37 => 'feature',
        0x38 => 'features',
        0x39 => 'feature-not-implemented',
        0x3a => 'field',
        0x3b => 'file',
        0x3c => 'filehash',
        0x3d => 'first',
        0x3e => 'free',
        0x3f => 'from',
        0x40 => 'g.us',
        0x41 => 'gcm',
        0x42 => 'get',
        0x43 => 'google',
        0x44 => 'group',
        0x45 => 'groups',
        0x46 => 'groups_v2',
        0x47 => 'http://etherx.jabber.org/streams',
        0x48 => 'http://jabber.org/protocol/chatstates',
        0x49 => 'ib',
        0x4a => 'id',
        0x4b => 'image',
        0x4c => 'img',
        0x4d => 'index',
        0x4e => 'internal-server-error',
        0x4f => 'ip',
        0x50 => 'iq',
        0x51 => 'item-not-found',
        0x52 => 'item',
        0x53 => 'jabber:iq:last',
        0x54 => 'jabber:iq:privacy',
        0x55 => 'jabber:x:event',
        0x56 => 'jid',
        0x57 => 'kind',
        0x58 => 'last',
        0x59 => 'leave',
        0x5a => 'list',
        0x5b => 'max',
        0x5c => 'mechanism',
        0x5d => 'media',
        0x5e => 'message_acks',
        0x5f => 'message',
        0x60 => 'method',
        0x61 => 'microsoft',
        0x62 => 'mimetype',
        0x63 => 'missing',
        0x64 => 'modify',
        0x65 => 'msg',
        0x66 => 'mute',
        0x67 => 'name',
        0x68 => 'nokia',
        0x69 => 'none',
        0x6a => 'not-acceptable',
        0x6b => 'not-allowed',
        0x6c => 'not-authorized',
        0x6d => 'notification',
        0x6e => 'notify',
        0x6f => 'off',
        0x70 => 'offline',
        0x71 => 'order',
        0x72 => 'owner',
        0x73 => 'owning',
        0x74 => 'p_o',
        0x75 => 'p_t',
        0x76 => 'paid',
        0x77 => 'participant',
        0x78 => 'participants',
        0x79 => 'participating',
        0x7a => 'paused',
        0x7b => 'picture',
        0x7c => 'pin',
        0x7d => 'ping',
        0x7e => 'pkmsg',
        0x7f => 'platform',
        0x80 => 'port',
        0x81 => 'presence',
        0x82 => 'preview',
        0x83 => 'probe',
        0x84 => 'prop',
        0x85 => 'props',
        0x86 => 'qcount',
        0x87 => 'query',
        0x88 => 'raw',
        0x89 => 'read',
        0x8a => 'readreceipts',
        0x8b => 'reason',
        0x8c => 'receipt',
        0x8d => 'relay',
        0x8e => 'remote-server-timeout',
        0x8f => 'remove',
        0x90 => 'request',
        0x91 => 'required',
        0x92 => 'resource-constraint',
        0x93 => 'resource',
        0x94 => 'response',
        0x95 => 'result',
        0x96 => 'retry',
        0x97 => 'rim',
        0x98 => 's_o',
        0x99 => 's_t',
        0x9a => 's.us',
        0x9b => 's.whatsapp.net',
        0x9c => 'seconds',
        0x9d => 'server-error',
        0x9e => 'server',
        0x9f => 'service-unavailable',
        0xa0 => 'set',
        0xa1 => 'show',
        0xa2 => 'silent',
        0xa3 => 'size',
        0xa4 => 'skmsg',
        0xa5 => 'stat',
        0xa6 => 'state',
        0xa7 => 'status',
        0xa8 => 'stream:error',
        0xa9 => 'stream:features',
        0xaa => 'subject',
        0xab => 'subscribe',
        0xac => 'success',
        0xad => 'sync',
        0xae => 't',
        0xaf => 'text',
        0xb0 => 'timeout',
        0xb1 => 'timestamp',
        0xb2 => 'tizen',
        0xb3 => 'to',
        0xb4 => 'true',
        0xb5 => 'type',
        0xb6 => 'unavailable',
        0xb7 => 'unsubscribe',
        0xb8 => 'upgrade',
        0xb9 => 'uri',
        0xba => 'url',
        0xbb => 'urn:ietf:params:xml:ns:xmpp-sasl',
        0xbc => 'urn:ietf:params:xml:ns:xmpp-stanzas',
        0xbd => 'urn:ietf:params:xml:ns:xmpp-streams',
        0xbe => 'urn:xmpp:ping',
        0xbf => 'urn:xmpp:whatsapp:account',
        0xc0 => 'urn:xmpp:whatsapp:dirty',
        0xc1 => 'urn:xmpp:whatsapp:mms',
        0xc2 => 'urn:xmpp:whatsapp:push',
        0xc3 => 'urn:xmpp:whatsapp',
        0xc4 => 'user',
        0xc5 => 'user-not-found',
        0xc6 => 'v',
        0xc7 => 'value',
        0xc8 => 'version',
        0xc9 => 'voip',
        0xca => 'w:g',
        0xcb => 'w:p:r',
        0xcc => 'w:p',
        0xcd => 'w:profile:picture',
        0xce => 'w',
        0xcf => 'wait',
        0xd0 => 'WAUTH-2',
        0xd1 => 'xmlns:stream',
        0xd2 => 'xmlns',
        0xd3 => '1',
        0xd4 => 'chatstate',
        0xd5 => 'crypto',
        0xd6 => 'phash',
        0xd7 => 'enc',
        0xd8 => 'class',
        0xd9 => 'off_cnt',
        0xda => 'w:g2',
        0xdb => 'promote',
        0xdc => 'demote',
        0xdd => 'creator',
        0xde => 'background',
        0xdf => 'backoff',
        0xe0 => 'chunked',
        0xe1 => 'context',
        0xe2 => 'full',
        0xe3 => 'in',
        0xe4 => 'interactive',
        0xe5 => 'out',
        0xe6 => 'registration',
        0xe7 => 'sid',
        0xe8 => 'urn:xmpp:whatsapp:sync',
        0xe9 => 'flt',
        0xea => 's16',
        0xeb => 'u8',
    );

    public static $map2 = array(
        0x00 => 'adpcm',
        0x01 => 'amrnb',
        0x02 => 'amrwb',
        0x03 => 'mp3',
        0x04 => 'pcm',
        0x05 => 'qcelp',
        0x06 => 'wma',
        0x07 => 'h263',
        0x08 => 'h264',
        0x09 => 'jpeg',
        0x0a => 'mpeg4',
        0x0b => 'wmv',
        0x0c => 'audio/3gpp',
        0x0d => 'audio/aac',
        0x0e => 'audio/amr',
        0x0f => 'audio/mp4',
        0x10 => 'audio/mpeg',
        0x11 => 'audio/ogg',
        0x12 => 'audio/qcelp',
        0x13 => 'audio/wav',
        0x14 => 'audio/webm',
        0x15 => 'audio/x-caf',
        0x16 => 'audio/x-ms-wma',
        0x17 => 'image/gif',
        0x18 => 'image/jpeg',
        0x19 => 'image/png',
        0x1a => 'video/3gpp',
        0x1b => 'video/avi',
        0x1c => 'video/mp4',
        0x1d => 'video/mpeg',
        0x1e => 'video/quicktime',
        0x1f => 'video/x-flv',
        0x20 => 'video/x-ms-asf',
        0x21 => '302',
        0x22 => '400',
        0x23 => '401',
        0x24 => '402',
        0x25 => '403',
        0x26 => '404',
        0x27 => '405',
        0x28 => '406',
        0x29 => '407',
        0x2a => '409',
        0x2b => '410',
        0x2c => '500',
        0x2d => '501',
        0x2e => '503',
        0x2f => '504',
        0x30 => 'abitrate',
        0x31 => 'acodec',
        0x32 => 'app_uptime',
        0x33 => 'asampfmt',
        0x34 => 'asampfreq',
        0x35 => 'clear',
        0x36 => 'conflict',
        0x37 => 'conn_no_nna',
        0x38 => 'cost',
        0x39 => 'currency',
        0x3a => 'duration',
        0x3b => 'extend',
        0x3c => 'fps',
        0x3d => 'g_notify',
        0x3e => 'g_sound',
        0x3f => 'gone',
        0x40 => 'google_play',
        0x41 => 'hash',
        0x42 => 'height',
        0x43 => 'invalid',
        0x44 => 'jid-malformed',
        0x45 => 'latitude',
        0x46 => 'lc',
        0x47 => 'lg',
        0x48 => 'live',
        0x49 => 'location',
        0x4a => 'log',
        0x4b => 'longitude',
        0x4c => 'max_groups',
        0x4d => 'max_participants',
        0x4e => 'max_subject',
        0x4f => 'mode',
        0x50 => 'napi_version',
        0x51 => 'normalize',
        0x52 => 'orighash',
        0x53 => 'origin',
        0x54 => 'passive',
        0x55 => 'password',
        0x56 => 'played',
        0x57 => 'policy-violation',
        0x58 => 'pop_mean_time',
        0x59 => 'pop_plus_minus',
        0x5a => 'price',
        0x5b => 'pricing',
        0x5c => 'redeem',
        0x5d => 'Replaced by new connection',
        0x5e => 'resume',
        0x5f => 'signature',
        0x60 => 'sound',
        0x61 => 'source',
        0x62 => 'system-shutdown',
        0x63 => 'username',
        0x64 => 'vbitrate',
        0x65 => 'vcard',
        0x66 => 'vcodec',
        0x67 => 'video',
        0x68 => 'width',
        0x69 => 'xml-not-well-formed',
        0x6a => 'checkmarks',
        0x6b => 'image_max_edge',
        0x6c => 'image_max_kbytes',
        0x6d => 'image_quality',
        0x6e => 'ka',
        0x6f => 'ka_grow',
        0x70 => 'ka_shrink',
        0x71 => 'newmedia',
        0x72 => 'library',
        0x73 => 'caption',
        0x74 => 'forward',
        0x75 => 'c0',
        0x76 => 'c1',
        0x77 => 'c2',
        0x78 => 'c3',
        0x79 => 'clock_skew',
        0x7a => 'cts',
        0x7b => 'k0',
        0x7c => 'k1',
        0x7d => 'login_rtt',
        0x7e => 'm_id',
        0x7f => 'nna_msg_rtt',
        0x80 => 'nna_no_off_count',
        0x81 => 'nna_offline_ratio',
        0x82 => 'nna_push_rtt',
        0x83 => 'no_nna_con_count',
        0x84 => 'off_msg_rtt',
        0x85 => 'on_msg_rtt',
        0x86 => 'stat_name',
        0x87 => 'sts',
        0x88 => 'suspect_conn',
        0x89 => 'lists',
        0x8a => 'self',
        0x8b => 'qr',
        0x8c => 'web',
        0x8d => 'w:b',
        0x8e => 'recipient',
        0x8f => 'w:stats',
        0x90 => 'forbidden',
        0x91 => 'max_list_recipients',
        0x92 => 'en-AU',
        0x93 => 'en-GB',
        0x94 => 'es-MX',
        0x95 => 'pt-PT',
        0x96 => 'zh-Hans',
        0x97 => 'zh-Hant',
        0x98 => 'relayelection',
        0x99 => 'relaylatency',
        0x9a => 'interruption',
        0x9b => 'Bell.caf',
        0x9c => 'Boing.caf',
        0x9d => 'Glass.caf',
        0x9e => 'Harp.caf',
        0x9f => 'TimePassing.caf',
        0xa0 => 'Tri-tone.caf',
        0xa1 => 'Xylophone.caf',
        0xa2 => 'aurora.m4r',
        0xa3 => 'bamboo.m4r',
        0xa4 => 'chord.m4r',
        0xa5 => 'circles.m4r',
        0xa6 => 'complete.m4r',
        0xa7 => 'hello.m4r',
        0xa8 => 'input.m4r',
        0xa9 => 'keys.m4r',
        0xaa => 'note.m4r',
        0xab => 'popcorn.m4r',
        0xac => 'pulse.m4r',
        0xad => 'synth.m4r',
        0xae => 'Apex.m4r',
        0xaf => 'Beacon.m4r',
        0xb0 => 'Bulletin.m4r',
        0xb1 => 'By The Seaside.m4r',
        0xb2 => 'Chimes.m4r',
        0xb3 => 'Circuit.m4r',
        0xb4 => 'Constellation.m4r',
        0xb5 => 'Cosmic.m4r',
        0xb6 => 'Crystals.m4r',
        0xb7 => 'Hillside.m4r',
        0xb8 => 'Illuminate.m4r',
        0xb9 => 'Night Owl.m4r',
        0xba => 'Opening.m4r',
        0xbb => 'Playtime.m4r',
        0xbc => 'Presto.m4r',
        0xbd => 'Radar.m4r',
        0xbe => 'Radiate.m4r',
        0xbf => 'Ripples.m4r',
        0xc0 => 'Sencha.m4r',
        0xc1 => 'Signal.m4r',
        0xc2 => 'Silk.m4r',
        0xc3 => 'Slow Rise.m4r',
        0xc4 => 'Stargaze.m4r',
        0xc5 => 'Summit.m4r',
        0xc6 => 'Twinkle.m4r',
        0xc7 => 'Uplift.m4r',
        0xc8 => 'Waves.m4r',
        0xc9 => 'eligible',
        0xca => 'planned',
        0xcb => 'current',
        0xcc => 'future',
        0xcd => 'disable',
        0xce => 'expire',
        0xcf => 'start',
        0xd0 => 'stop',
        0xd1 => 'accuracy',
        0xd2 => 'speed',
        0xd3 => 'bearing',
        0xd4 => 'recording',
        0xd5 => 'key',
        0xd6 => 'identity',
        0xd7 => 'w:gp2',
        0xd8 => 'admin',
        0xd9 => 'locked',
        0xda => 'unlocked',
        0xdb => 'new',
        0xdc => 'battery',
        0xdd => 'archive',
        0xde => 'adm',
        0xdf => 'plaintext_size',
        0xe0 => 'plaintext_disabled',
        0xe1 => 'plaintext_reenable_threshold',
        0xe2 => 'compressed_size',
        0xe3 => 'delivered',
        0xe4 => 'everyone',
        0xe5 => 'transport',
        0xe6 => 'mspes',
        0xe7 => 'e2e_groups',
        0xe8 => 'e2e_images',
        0xe9 => 'encr_media',
        0xea => 'encrypt_v2',
        0xeb => 'encrypt_image',
        0xec => 'encrypt_sends_push',
        0xed => 'force_long_connect',
        0xee => 'audio_opus',
        0xef => 'video_max_edge',
        0xf0 => 'call-id',
        0xf1 => 'call',
        0xf2 => 'preaccept',
        0xf3 => 'accept',
        0xf4 => 'offer',
        0xf5 => 'reject',
        0xf6 => 'busy',
        0xf7 => 'te',
        0xf8 => 'terminate',
        0xf9 => 'begin',
        0xfa => 'end',
        0xfb => 'opus',
        0xfc => 'rtt',
        0xfd => 'token',
        0xfe => 'priority',
        0xff => 'p2p'
    );

    public static $map3 = [
        0x00 => 'rate',
        0x01=> 'amr',
        0x02 => 'ptt',
        0x03 => 'srtp',
        0x04 => 'os',
        0x05 => 'browser',
        0x06 => 'encrypt_group_gen2',
        0x07 => 'encrypt_audio',
        0x08 => 'encrypt_blist',
        0x09 => 'encrypt_contact',
        0x0a => 'encrypt_location',
        0x0b => 'encrypt_url',
        0x0c => 'encrypt_video',
        0x0d => 'doc_types',
        0x0e => 'upload_oom_hprof_enabled',
        0x0f => 'tos',
        0x10 => 'client',
        0x11 => 'e2e_audio',
        0x12 => 'e2e_blists',
        0x13 => 'e2e_video',
        0x14 => 'document',
        0x15 => 'contact',
        0x16 => 'file_max_size',
        0x17 => 'small_call_btn',
        0x18 => 'enable_mp4_operations_mux',
        0x19 => 'android_vacuuming_enabled',
        0x1a => 'android_vacuum_experiment_enabled',
        0x1b => 'aec',
        0x1c => 'agc',
        0x1d => 'options',
        0x1e => 'encode',
        0x1f => 'bwe',
        0x20 => 'rc',
        0x21 => 'ns',
        0x22 => 'ec_threshold',
        0x23 => 'ec_off_threshold',
        0x24 => 'algorithm',
        0x25 => 'targetlevel',
        0x26 => 'compressiongain',
        0x27 => 'limiterenable',
        0x28 => 'cbr',
        0x29 => 'complexity',
        0x2a => 'minfpp',
        0x2b => 'maxrtt',
        0x2c => 'low_data_usage_bitrate',
        0x2d => 'usync',
        0x2e => 'refresh',
        0x2f => 'media_max_autodownload',
    ];

    /**
     * Get token by string
     * @param string $string token
     * @return int
     * @throws RuntimeException
     */
    public static function getToken($string){
        $token = array_search($string, self::$map1);
        if($token === false){
            $token = array_search($string, self::$map2);
            if($token !== false){
                $token = 0xEC00 | $token;
            }
        }
        if($token === false){
            $token = array_search($string, self::$map3);
            if($token !== false){
                $token = 0xED00 | $token;
            }
        }
        if($token === false){
            throw new RuntimeException(strtr('Token not found for :string', array(
                ':string' => $string,
            )));
        }
        return $token;
    }

    /**
     * Check whether token for stirng is exists
     * @param string $string string
     * @param null $dict
     * @return bool
     */
    public static function hasToken($string, $dict = null){
        switch($dict){
            case 0xED:
                return (bool)array_search($string, self::$map3);
                break;
            case 0xEC:
                return (bool)array_search($string, self::$map2);
                break;
            default:
                return (bool)array_search($string, self::$map1)
                || (bool)array_search($string, self::$map2);
            break;
        }

    }

    /**
     * Get string by token
     * @param $token
     * @param null $dict
     * @return mixed
     * @throws RuntimeException
     */
    public static function getString($token, $dict = null){
        switch($dict){
            case 0xED:
                $dictionary = self::$map3;
            break;
            case 0xEC:
                $dictionary = self::$map2;
            break;
            default:
                $dictionary = self::$map1;
            break;
        }
        if(!array_key_exists($token, $dictionary)){
            throw new RuntimeException(strtr('String not found for :token', array(
                ':token' => $token,
            )));
        }
        return $dictionary[$token];
    }
}